import type { Metadata } from "next";
import { Anonymous_Pro, Inter } from "next/font/google";
import "./globals.css";
import BottomNavigation from "@/components/ui/BottomNavigation";

const anonymousPro = Anonymous_Pro({
  variable: "--font-anonymous-pro",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const sfProText = Inter({
  variable: "--font-sf-pro-text",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App", 
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${anonymousPro.variable} ${sfProText.variable} antialiased`}
      >
        <div className="pb-[69px] bg-[#2F2F33]">
          {children}
        </div>
        <BottomNavigation />
      </body>
    </html>
  );
}
